<a href="https://colab.research.google.com/github/nikitaxdeshpande/nikitaxdeshpande/blob/main/GANs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#BUILDING A GAN MODEL IN PyTorch: GENERATOR
import torch.nn as nn # import the torch.nn module and alias it as nn

class Generator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(seq_length, seq_length),
        nn.Sigmoid()
    )
  def forward(self, x):
    return self.model(x)

In [8]:
#Building the discriminator network
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(sq_length, 1),
        nn.Sigmoid()
    )
  def forward(self, x):
    return self.model(x)


In [10]:
#BUILDING A GAN MODEL IN PyTorch: GENERATOR
import torch.nn as nn # import the torch.nn module and alias it as nn

# Define seq_length
seq_length = 100 # Example value, set to the desired sequence length

class Generator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(seq_length, seq_length),
        nn.Sigmoid()
    )
  def forward(self, x):
    return self.model(x)

In [26]:
#Training the discriminator

import torch

# Example real_data (replace with your actual data)
real_data = torch.randn(seq_length)

# Instantiate the discriminator
discriminator = Discriminator()
generator = Generator()

criterion = nn.BCELoss() # Example: Binary Cross Entropy Loss

# Define the optimizer
optimizer_discriminator = torch.optim.Adam(discriminator.parameters())

num_epochs = 50
for epoch in range(num_epochs):
  for real_data_item in real_data.unsqueeze(0): # Changed loop variable to avoid shadowing
    noise = torch.rand((1, seq_length))
    disc_real = discriminator(real_data_item) # Use real_data_item here
    fake_data = generator(noise)
    disc_fake = discriminator(fake_data.detach())
    loss_disc = criterion(disc_real, torch.ones_like(disc_real))+ criterion(disc_fake, torch.zeros_like(disc_fake))
    optimizer_discriminator.zero_grad()
    loss_disc.backward()
    optimizer_discriminator.step()

In [21]:
#Building the discriminator network
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(seq_length, 1), # Changed sq_length to seq_length
        nn.Sigmoid()
    )
  def forward(self, x):
    return self.model(x)

In [20]:
#Building the discriminator network
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(seq_length, 1), # Changed sq_length to seq_length
        nn.Sigmoid()
    )
  def forward(self, x):
    return self.model(x)

In [29]:
#Training the Generator
import torch
# Instantiate the discriminator
discriminator = Discriminator()
generator = Generator()

criterion = nn.BCELoss() # Example: Binary Cross Entropy Loss

# Define the optimizer
optimizer_discriminator = torch.optim.Adam(discriminator.parameters())
optimizer_generator = torch.optim.Adam(generator.parameters()) # Define optimizer_generator

num_epochs = 50
for epoch in range(num_epochs):
  for real_data_item in real_data.unsqueeze(0): # Changed loop variable to avoid shadowing
    # Discriminator training
    noise = torch.rand((1, seq_length))
    disc_real = discriminator(real_data_item) # Use real_data_item here
    fake_data = generator(noise)
    disc_fake = discriminator(fake_data.detach())
    loss_disc = criterion(disc_real, torch.ones_like(disc_real))+ criterion(disc_fake, torch.zeros_like(disc_fake))
    optimizer_discriminator.zero_grad()
    loss_disc.backward()
    optimizer_discriminator.step()

    #Generator training
    disc_fake = discriminator(fake_data)
    loss_gen = criterion(disc_fake, torch.ones_like(disc_fake))
    optimizer_generator.zero_grad() # Now you can use optimizer_generator
    loss_gen.backward()
    optimizer_generator.step()
    if (epoch+1)%10 == 0:
      print(f"Epoch {epoch+1}/{num_epochs}:\t\
            Generator loss: {loss_gen.item()}\t\
            Discriminator loss: {loss_disc.item()}")

Epoch 10/50:	            Generator loss: 0.4518023133277893	            Discriminator loss: 1.33694589138031
Epoch 20/50:	            Generator loss: 0.4350324273109436	            Discriminator loss: 1.281173825263977
Epoch 30/50:	            Generator loss: 0.506084144115448	            Discriminator loss: 1.123232126235962
Epoch 40/50:	            Generator loss: 0.5490851402282715	            Discriminator loss: 1.0410257577896118
Epoch 50/50:	            Generator loss: 0.6610575318336487	            Discriminator loss: 0.8881955146789551


In [31]:
#Printing Real and Generated Data

print("\nReal Data: ")
print(real_data[:5]) # Changed 'data' to 'real_data'

print("\nGenerated Data: ")
for _ in range(5):
  noise = torch.rand((1, seq_length))
  generated_data = generator(noise)
  print(torch.round(generated_data).detach())


Real Data: 
tensor([-0.1439, -2.1032, -0.6928,  1.4095, -0.3166])

Generated Data: 
tensor([[0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
         1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
         0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
         0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
         1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
         1., 1., 0., 0., 1., 1., 0., 0., 1., 0.]])
tensor([[0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
         1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
         0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
         0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
         1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
         1., 1., 0., 0., 0., 1., 0., 0., 1., 0.]])
ten